# Consider the below code to answer further questions:

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

__Ans. :__<br>

Yes, there is a difference in the data type of variables __list___ and __array_list__.

The variable __list___ is a Python list, whereas the variable __array_list__ is a NumPy array.

To print the data types of both variables, we can use the __type()__ function:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [5]:
list_ = ['1', '2', '3', '4', '5']

for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
array_list = np.array(object=list_)

for element in array_list:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ andarra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

__Ans. :__<br>

Yes, there will be a difference in the data type of the elements present in __list___ and __array_list__ after the following change:

In [7]:
array_list = np.array(object=list_, dtype=int)

In this case, we are explicitly specifying the dtype parameter as int, which will convert the elements in __list___ to integer type when creating the NumPy array __array_list__.

In [8]:
import numpy as np

# Original list
list_ = ['1', '2', '3', '4', '5']

# NumPy array with integer type
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print(type(element))
    
# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# Consider the below code to answer further questions:

In [4]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape

In [9]:
# Print the shape of num_array
print(num_array.shape)

(2, 3)


### (ii) size

In [10]:
# Print the size of num_array
print(num_array.size)

6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [11]:
import numpy as np

# Create a NumPy array of a 3x3 matrix containing zeros
zeros_array = np.zeros(shape=(3, 3))

# Print the zeros_array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [12]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.identity(n=5)

# Print the identity_matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
